fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      branch: '4.11.x'
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile.git
      branch: '1.4.x'
    wget:
      repo: git://github.com/maestrodev/puppet-wget.git
  symlinks:
    teamcity: "#{source_dir}"